## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=["EIN", "NAME"], inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()

# Display unique values
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Display value counts
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
# Set the cutoff value
cutoff = 500

# Determine which application types to replace
application_types_to_replace = application_type_counts[application_type_counts < cutoff].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Display value counts
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
# Filter classification_counts for counts > 1
classification_counts = classification_counts[classification_counts > 1]

# Display value counts greater than 1
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

# Set the cutoff value
cutoff = 1000

# Determine which classifications to replace
classifications_to_replace = classification_counts[classification_counts < cutoff].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2235
C3000     1918
C2100     1883
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1248        1
C2600        1
C1580        1
C6100        1
C1820        1
C1900        1
C2570        1
C1570        1
C3700        1
C2500        1
C1283        1
C2380        1
C1732        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

In [10]:
# Split our preprocessed data into our features and target arrays
# Features are all columns except the target column
X = application_df.drop(columns=["IS_SUCCESSFUL"])

# Target is the "IS_SUCCESSFUL" column
y = application_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=84, stratify=y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=256, activation="relu", input_dim=X_train.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=128, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation="relu"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 256)               17920

 dense_1 (Dense)             (None, 128)               32896

 dense_2 (Dense)             (None, 64)                8256

 dense_3 (Dense)             (None, 32)                2080

 dense_4 (Dense)             (None, 1)                 33

=================================================================
Total params: 61185 (239.00 KB)
Trainable params: 61185 (239.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50, shuffle=True, verbose=2)
fit_model

Epoch 1/50
804/804 - 8s - loss: 0.5670 - accuracy: 0.7247 - 8s/epoch - 10ms/step
Epoch 2/50
804/804 - 2s - loss: 0.5550 - accuracy: 0.7310 - 2s/epoch - 2ms/step
Epoch 3/50
804/804 - 2s - loss: 0.5508 - accuracy: 0.7322 - 2s/epoch - 2ms/step
Epoch 4/50
804/804 - 2s - loss: 0.5492 - accuracy: 0.7347 - 2s/epoch - 2ms/step
Epoch 5/50
804/804 - 3s - loss: 0.5485 - accuracy: 0.7336 - 3s/epoch - 4ms/step
Epoch 6/50
804/804 - 2s - loss: 0.5475 - accuracy: 0.7348 - 2s/epoch - 3ms/step
Epoch 7/50
804/804 - 2s - loss: 0.5458 - accuracy: 0.7350 - 2s/epoch - 2ms/step
Epoch 8/50
804/804 - 2s - loss: 0.5456 - accuracy: 0.7335 - 2s/epoch - 2ms/step
Epoch 9/50
804/804 - 2s - loss: 0.5451 - accuracy: 0.7359 - 2s/epoch - 2ms/step
Epoch 10/50
804/804 - 2s - loss: 0.5442 - accuracy: 0.7373 - 2s/epoch - 2ms/step
Epoch 11/50
804/804 - 3s - loss: 0.5438 - accuracy: 0.7365 - 3s/epoch - 4ms/step
Epoch 12/50
804/804 - 2s - loss: 0.5432 - accuracy: 0.7363 - 2s/epoch - 2ms/step
Epoch 13/50
804/804 - 2s - loss: 0.5423 - accuracy: 0.7375 - 2s/epoch - 2ms/step
Epoch 14/50
804/804 - 2s - loss: 0.5419 - accuracy: 0.7374 - 2s/epoch - 2ms/step
Epoch 15/50
804/804 - 2s - loss: 0.5414 - accuracy: 0.7374 - 2s/epoch - 2ms/step
Epoch 16/50
804/804 - 2s - loss: 0.5410 - accuracy: 0.7373 - 2s/epoch - 2ms/step
Epoch 17/50
804/804 - 2s - loss: 0.5410 - accuracy: 0.7383 - 2s/epoch - 3ms/step
Epoch 18/50
804/804 - 2s - loss: 0.5408 - accuracy: 0.7379 - 2s/epoch - 2ms/step
Epoch 19/50
804/804 - 2s - loss: 0.5400 - accuracy: 0.7392 - 2s/epoch - 2ms/step
Epoch 20/50
804/804 - 2s - loss: 0.5393 - accuracy: 0.7391 - 2s/epoch - 2ms/step
Epoch 21/50
804/804 - 2s - loss: 0.5396 - accuracy: 0.7388 - 2s/epoch - 2ms/step
Epoch 22/50
804/804 - 2s - loss: 0.5390 - accuracy: 0.7393 - 2s/epoch - 3ms/step
Epoch 23/50
804/804 - 2s - loss: 0.5387 - accuracy: 0.7402 - 2s/epoch - 3ms/step
Epoch 24/50
804/804 - 2s - loss: 0.5386 - accuracy: 0.7390 - 2s/epoch - 3ms/step
Epoch 25/50
804/804 - 2s - loss: 0.5379 - accuracy: 0.7395 - 2s/epoch - 2ms/step
Epoch 26/50
804/804 - 2s - loss: 0.5377 - accuracy: 0.7398 - 2s/epoch - 2ms/step
Epoch 27/50
804/804 - 2s - loss: 0.5375 - accuracy: 0.7405 - 2s/epoch - 2ms/step
Epoch 28/50
804/804 - 2s - loss: 0.5371 - accuracy: 0.7402 - 2s/epoch - 3ms/step
Epoch 29/50
804/804 - 2s - loss: 0.5367 - accuracy: 0.7402 - 2s/epoch - 2ms/step
Epoch 30/50
804/804 - 3s - loss: 0.5361 - accuracy: 0.7399 - 3s/epoch - 3ms/step
Epoch 31/50
804/804 - 2s - loss: 0.5368 - accuracy: 0.7399 - 2s/epoch - 2ms/step
Epoch 32/50
804/804 - 2s - loss: 0.5354 - accuracy: 0.7408 - 2s/epoch - 2ms/step
Epoch 33/50
804/804 - 2s - loss: 0.5364 - accuracy: 0.7404 - 2s/epoch - 2ms/step
Epoch 34/50
804/804 - 2s - loss: 0.5356 - accuracy: 0.7403 - 2s/epoch - 2ms/step
Epoch 35/50
804/804 - 2s - loss: 0.5359 - accuracy: 0.7413 - 2s/epoch - 2ms/step
Epoch 36/50
804/804 - 3s - loss: 0.5350 - accuracy: 0.7411 - 3s/epoch - 3ms/step
Epoch 37/50
804/804 - 2s - loss: 0.5356 - accuracy: 0.7413 - 2s/epoch - 2ms/step
Epoch 38/50
804/804 - 2s - loss: 0.5350 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 39/50
804/804 - 2s - loss: 0.5345 - accuracy: 0.7413 - 2s/epoch - 2ms/step
Epoch 40/50
804/804 - 2s - loss: 0.5347 - accuracy: 0.7411 - 2s/epoch - 2ms/step
Epoch 41/50
804/804 - 2s - loss: 0.5407 - accuracy: 0.7408 - 2s/epoch - 2ms/step
Epoch 42/50
804/804 - 2s - loss: 0.5341 - accuracy: 0.7407 - 2s/epoch - 3ms/step
Epoch 43/50
804/804 - 3s - loss: 0.5337 - accuracy: 0.7414 - 3s/epoch - 3ms/step
Epoch 44/50
804/804 - 2s - loss: 0.5337 - accuracy: 0.7414 - 2s/epoch - 2ms/step
Epoch 45/50
804/804 - 2s - loss: 0.5336 - accuracy: 0.7417 - 2s/epoch - 2ms/step
Epoch 46/50
804/804 - 2s - loss: 0.5345 - accuracy: 0.7411 - 2s/epoch - 2ms/step
Epoch 47/50
804/804 - 2s - loss: 0.5376 - accuracy: 0.7411 - 2s/epoch - 2ms/step
Epoch 48/50
804/804 - 2s - loss: 0.5328 - accuracy: 0.7415 - 2s/epoch - 2ms/step
Epoch 49/50
804/804 - 3s - loss: 0.5334 - accuracy: 0.7411 - 3s/epoch - 3ms/step
Epoch 50/50
804/804 - 2s - loss: 0.5328 - accuracy: 0.7412 - 2s/epoch - 2ms/step

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Print the model's loss and accuracy
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5701 - accuracy: 0.7250 - 999ms/epoch - 4ms/step
Loss: 0.5701320767402649, Accuracy: 0.7250145673751831

In [16]:

# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization_Run1.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(