## Preprocessing

In [11]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [12]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_new_df = application_df.drop(columns=["EIN"], axis=1)
application_new_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [13]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()

# Display unique values
unique_values

EIN                       34299
NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [14]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Display value counts
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [25]:
# DUPE OF APPLICATION TYPES...UPDATE AS NEEDED
# Choose a cutoff value and create a list of names to be replaced
cutoff_value = 50
# Create a list of Names to be replaced
application_types_to_replace = application_new_df['NAME'].value_counts()[application_new_df['NAME'].value_counts() < cutoff_value].index.tolist()
# Replace in dataframe
for app in application_types_to_replace:
    application_new_df['NAME'] = application_new_df['NAME'].replace(app,"Other")

# Check to make sure binning was successful
application_new_df['NAME'].value_counts()

NAME
Other                                                                 24545
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
MONTANA 4-H FOUNDATION INC                                              107
HONOR SOCIETY OF PHI KAPPA PHI                                          107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
AIR FORCE ASSOCIATION                                                    99
WORKERS UNITED                                                           97
GAMMA THETA UPSILON                                                      92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                               91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                  87
ROTARY INTERNATIONAL                                                     84
CALIFORNIA GARDEN CLUBS INC                                              76
SWEET ADELINES INTERNATIONAL                                             73
DISABLED AMERICAN VETERANS                                               73
KLEIN SUPPORT GROUPS INC                                                 69
CLEARCREEK I S D SUPPORT GROUPS                                          60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                 58
CISD EDUCATIONAL SUPPORT GROUPS INC                                      57
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC           57
SONS OF CONFEDERATE VETERANS INC                                         56
SLOW FOOD USA INC                                                        55
NATIONAL YOUNG MENS SERVICE LEAGUE                                       54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                              52
LAMBDA THETA ALPHA                                                       52
UNITED FEDERATION OF DOLL CLUBS INC                                      50
UNIVERSITY OF FLORIDA                                                    50
Name: count, dtype: int64

In [18]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
# Set the cutoff value
cutoff = 100

application_types_to_replace = application_type_counts[application_type_counts < cutoff].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [19]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Display value counts
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [20]:
# You may find it helpful to look at CLASSIFICATION value counts >1
# Filter classification_counts for counts > 1
classification_counts = classification_counts[classification_counts > 1]

# Display value counts greater than 1
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [22]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

# Set the cutoff value
cutoff = 125

classifications_to_replace = application_new_df['CLASSIFICATION'].value_counts()[application_new_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_new_df['CLASSIFICATION'] = application_new_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_new_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      391
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
Name: count, dtype: int64

In [23]:
# Convert categorical data to numeric with `pd.get_dummies`
data_encoded = pd.get_dummies(application_df)

In [24]:
# Split our preprocessed data into our features and target arrays
X = data_encoded.drop(["IS_SUCCESSFUL"], axis='columns').values
y = data_encoded["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [26]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [27]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()
number_input_features = len(X_train[0])
hidden_layer1 = 100
hidden_layer2 = 30
hidden_layer3 = 10

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer1, activation="relu", input_dim=number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               1967900

 dense_1 (Dense)             (None, 30)                3030

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 1971251 (7.52 MB)
Trainable params: 1971251 (7.52 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [29]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)
fit_model

Epoch 1/50
804/804 [==============================] - 13s 15ms/step - loss: 0.4773 - accuracy: 0.7717
Epoch 2/50
804/804 [==============================] - 12s 14ms/step - loss: 0.1349 - accuracy: 0.9497
Epoch 3/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0977 - accuracy: 0.9608
Epoch 4/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0931 - accuracy: 0.9619
Epoch 5/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0919 - accuracy: 0.9628
Epoch 6/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0907 - accuracy: 0.9628
Epoch 7/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0906 - accuracy: 0.9630
Epoch 8/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0895 - accuracy: 0.9629
Epoch 9/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0892 - accuracy: 0.9635
Epoch 10/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0882 - accuracy: 0.9638
Epoch 11/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0877 - accuracy: 0.9636
Epoch 12/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0878 - accuracy: 0.9642
Epoch 13/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0870 - accuracy: 0.9647
Epoch 14/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0868 - accuracy: 0.9646
Epoch 15/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0866 - accuracy: 0.9650
Epoch 16/50
804/804 [==============================] - 12s 14ms/step - loss: 0.0864 - accuracy: 0.9648
Epoch 17/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0852 - accuracy: 0.9651
Epoch 18/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0851 - accuracy: 0.9651
Epoch 19/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0847 - accuracy: 0.9654
Epoch 20/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0843 - accuracy: 0.9658
Epoch 21/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0837 - accuracy: 0.9657
Epoch 22/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0835 - accuracy: 0.9663
Epoch 23/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0828 - accuracy: 0.9665
Epoch 24/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0829 - accuracy: 0.9662
Epoch 25/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0827 - accuracy: 0.9660
Epoch 26/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0823 - accuracy: 0.9668
Epoch 27/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0816 - accuracy: 0.9667
Epoch 28/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0812 - accuracy: 0.9669
Epoch 29/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0810 - accuracy: 0.9668
Epoch 30/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0805 - accuracy: 0.9669
Epoch 31/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0803 - accuracy: 0.9670
Epoch 32/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0796 - accuracy: 0.9675
Epoch 33/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0800 - accuracy: 0.9678
Epoch 34/50
804/804 [==============================] - 12s 14ms/step - loss: 0.0791 - accuracy: 0.9672
Epoch 35/50
804/804 [==============================] - 12s 14ms/step - loss: 0.0793 - accuracy: 0.9678
Epoch 36/50
804/804 [==============================] - 12s 14ms/step - loss: 0.0785 - accuracy: 0.9678
Epoch 37/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0783 - accuracy: 0.9680
Epoch 38/50
804/804 [==============================] - 12s 14ms/step - loss: 0.0777 - accuracy: 0.9680
Epoch 39/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0776 - accuracy: 0.9685
Epoch 40/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0779 - accuracy: 0.9679
Epoch 41/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0770 - accuracy: 0.9684
Epoch 42/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0765 - accuracy: 0.9685
Epoch 43/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0764 - accuracy: 0.9684
Epoch 44/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0782 - accuracy: 0.9685
Epoch 45/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0756 - accuracy: 0.9691
Epoch 46/50
804/804 [==============================] - 13s 16ms/step - loss: 0.0758 - accuracy: 0.9692
Epoch 47/50
804/804 [==============================] - 12s 16ms/step - loss: 0.0752 - accuracy: 0.9686
Epoch 48/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0756 - accuracy: 0.9688
Epoch 49/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0750 - accuracy: 0.9693
Epoch 50/50
804/804 [==============================] - 12s 15ms/step - loss: 0.0748 - accuracy: 0.9693

In [30]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Print the model's loss and accuracy
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.6138 - accuracy: 0.7615 - 1s/epoch - 5ms/step
Loss: 0.6137787699699402, Accuracy: 0.7615160346031189

In [31]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization_Run3.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(